### ISSUE TITLE
Provide GitHub Releases

### ISSUE THREAD

**Issue by schrieveslaach** [testforstephen/vscode-pde#38]
It would be great if new versions (and maybe the release 0.6.0) would be available as GitHub release because that allows to download the versions through scripting. Downloads of plugins via `curl` are prohibited by VSCode marketplace.

I created a plugin for Neovim ([`nvim-jdtls-bundles`](https://gitlab.com/schrieveslaach/nvim-jdtls-bundles)) that downloads VSCode extensions from GitHub and sets up eclipse.jdt.ls to use the contained Java libs as plugins. However, for vscode-pde I have to commit the vslx file to the repo (see [here](https://gitlab.com/schrieveslaach/nvim-jdtls-bundles/-/blob/main/yaozheng.vscode-pde-0.6.0.vsix)) so users of the plugin also have to install git lfs.

**Comment by testforstephen** [comment]
Closing it since 0.7.0 has been created on Release page.

**Comment by schrieveslaach** [comment]
Thank you very much. I appreciate that change.
