### ISSUE TITLE
Consider packaging org.eclipse.m2e.pde.target to add Maven artifact support to target files

### ISSUE THREAD

**Issue by rgrunber** [testforstephen/vscode-pde#42]
Eclipse PDE has support for converting Maven artifacts into OSGi bundles dynamically. One can use a target file like : https://github.com/eclipse/lsp4mp/blob/d9a55eb9bbb19e8a88c0d94accef730b4b055fa5/microprofile.jdt/org.eclipse.lsp4mp.jdt.tp/org.eclipse.lsp4mp.jdt.target .

![Screenshot from 2022-08-19 20-10-33](https://user-images.githubusercontent.com/1417342/185721458-25db7970-6d16-4ff9-94f0-956cc4b55348.png)

~~Current issue is that `org.eclipse.m2e.pde.target` depends on [`org.eclipse.pde.ui`](https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.pde.target/META-INF/MANIFEST.MF#L9) which is a UI component. However, nothing in the plugin should require it from what I can tell. Even the extension it uses comes from pde.core.~~ Fixed with https://github.com/eclipse-m2e/m2e-core/commit/6259d8e86cb207bff1c62a6a5e6dc68ae8671507 .

**Comment by rgrunber** [comment]
https://download.eclipse.org/technology/m2e/snapshots/2.0.2/ (towards the 2.0.2 or 2.1.0 release) should contain a version of `org.eclipse.m2e.pde.target 2.0.1` that does not depend on any UI components.

I think the additional dependencies introduced would be :

16K	org.eclipse.m2e.workspace.cli_0.3.1.jar
36K	org.osgi.service.repository_1.1.0.201505202024.jar
72K	org.eclipse.m2e.pde.target_2.0.1.20220822-2010.jar
452K	biz.aQute.bnd.util_6.3.1.202206071316.jar
600K	org.eclipse.m2e.core_2.0.1.20220820-1147.jar
2.9M	com.google.guava_30.1.0.v20210127-2300.jar
3.2M	biz.aQute.bndlib_6.3.1.202206071316.jar
5.7M	org.eclipse.m2e.maven.runtime_3.8.601.20220820-1147

**Comment by rgrunber** [comment]
Note that this could be considered lower priority for now. As it happens in lsp4mp, we actually found a way to avoid using maven artifacts for now (basically Guava does what we need and it's available in the JDT-LS runtime).

However the motivation from this comes from https://www.eclipse.org/lists/cross-project-issues-dev/msg19066.html . So at some point, we may want latest version of the contents from within the Orbit repo at https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target#L10 , and they may only be available as Maven artifacts, which will mean for developers to resolve that target file in vscode-pde, they'll depend on this issue.

**Comment by mickaelistria** [comment]
Maven artifacts in .target are getting very mainstream, JDT, Platform, Equinox, LSP4E, TM4E, CDT, Wild Web Developer and JDT-LS since https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2826 ... are all using them. So it's now high priority to support it

**Comment by rgrunber** [comment]
This appears to be working with https://github.com/testforstephen/vscode-pde/commit/74c2a1c2897abbb6dc6e00b71c20041eca2f234e .

**Comment by testforstephen** [comment]
I forgot to update the issue. Yes, this has been fixed in vscode-pde@0.10.0.
