### ISSUE TITLE
How custom P2 mirror? Help

### ISSUE THREAD

**Issue by mozhuanzuojing** [testforstephen/vscode-pde#51]
I specified a domestic mirror address in the target file, but when reloading target, it went to find a different mirror address

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="Java Decompiler Target Definition" sequenceNumber="1">
    <locations>
        <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
            <unit id="org.eclipse.jdt.source.feature.group" version="3.19.0.v20230302-0300"/>
            <repository location="http://mirrors.ustc.edu.cn/eclipse/releases/2023-03/202303151000/"/>
	        <unit id="org.eclipse.sdk.feature.group" version="4.27.0.v20230302-0300"/>
        </location>
        <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
            <unit id="org.eclipse.jdt.ls.core" version="0.0.0"/>
            <repository location="https://download.eclipse.org/jdtls/snapshots/repository/latest/"/>
        </location>
    </locations>
    <targetJRE path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17"/>
</target>
```

##### screen
![image](https://user-images.githubusercontent.com/63572041/224589302-1874f434-7e46-46a3-865f-794311336aab.png)

##### addtional
this is my project: https://gitee.com/mozhuanzuojing/jdec.jdt.ls.decompiler.git

**Comment by testforstephen** [comment]
It may be related with p2 cache, you can try "F1 -> Java: Clean Java Language Server Workspace".

**Comment by mozhuanzuojing** [comment]
> It may be related with p2 cache, you can try "F1 -> Java: Clean Java Language Server Workspace".

Thanks for your reply, I have intercepted the `www.eclipse.org/downloads/download.php` via proxy server `whistle`, replacing the proxy address of the response. It is now possible to download successfully
