### ISSUE TITLE
Any plan on publishing the extension on Open VSX Registry?

### ISSUE THREAD

**Issue by mattdibi** [testforstephen/vscode-pde#54]
Hello there!

As per title: is there any plan on publishing the _vscode-pde_ extension on the [Open VSX Registry](https://open-vsx.org/)?

This would help foster adoption of the extension for users of

- [VSCodium](https://vscodium.com/)
- [Arch Linux distribution of Code - OSS](https://wiki.archlinux.org/title/Visual_Studio_Code)
- [Gitpod](https://www.gitpod.io/)
- [Eclipse Theia](https://theia-ide.org/)

While it's still possible to install the extension on those editors by use of specific commands, it is quite a lot easier to navigate the marketplace to perform the same action.

I think it would be a good fit since the Registry is an Eclipse Foundation project itself and this extension is closely tied to other Eclipse projects which were already published on that same registry.

**Comment by testforstephen** [comment]
Sorry, we don't have the capability to maintain an additional publish at this time. We developed this project to try out eclipse.jdt.ls development in vscode ourselves. It has limited functionalities and we lack the resources to implement the full pde features.

**Comment by mattdibi** [comment]
That's fair! Thank you for the transparency and the insight :)
