### ISSUE TITLE
pde project cannot be imported successfully, unless exist `.project` `.settings` `.classpath`

### ISSUE THREAD

**Issue by mozhuanzuojing** [testforstephen/vscode-pde#56]
> I have a decompiled project `https://gitee.com/mozhuanzuojing/jdec.jdt.ls.decompiler` that it never works to import of `vscode-java`, until yesterday when I accidentally opened it with `eclipse` and automatically added `.project` `.settings` `.classpath`, Then `vscode-java` can actually be imported it and developed normally.

I wonder if the pde project must have these three files [`.project` `.settings` `.classpath`]?

**Comment by testforstephen** [comment]
correct, you must generate such config files by yourself, for example, use Eclipse to generate them. This extension only supports importing an existing eclipse pde project.

**Comment by testforstephen** [comment]
If you prefer not to set up Eclipse IDE to generate these metadata files, you can simply copy them from an existing PDE project, such as https://github.com/testforstephen/vscode-pde/tree/master/pde/org.eclipse.jdt.ls.importer.pde. After copying, be sure to adjust the project name and Java version in the metadata files as needed.

**Comment by mattdibi** [comment]
Is that simple?!?! OMG I was way overcomplicating things. This means that I could create a template and a simple script to autogenerate everything... This was extremely helpful! Thanks @testforstephen !

**Comment by testforstephen** [comment]
These metadata files are quite similar, using some template to generate them should work.
